<?php
declare(strict_types=1);

namespace App\Helpers;

/**
 * Class AllColors
 * @package App\Helpers
 */
class AllColors{
    protected $colors = [
    'Light pastel purple',
    'Nintendo red',
    'White smoke',
    'React Native pink',
    'Dark vanilla',
    'Pineapple',
    'Lemon yellow Crayola',
    'Orchid Crayola',
    'Raspberry',
    'Mustard yellow',
    'Red orange',
    'Light khaki',
    'Cadet',
    'Maroon Crayola',
    'Carnelian',
    'English lavender',
    'Wild watermelon',
    'Royal yellow',
    'Charleston green',
    'Catawba',
    'Purple X11',
    'Red cola',
    'Trolley grey',
    'Registration black',
    'Terra cotta',
    'Apple green',
    'Eminence',
    'Pink pearl',
    'Dark magenta',
    'Light moss green',
    'Puce',
    'Grullo',
    'Acid green',
    'Peach Crayola',
    'Pastel yellow',
    'Olive',
    'Desert sand',
    'Gold metallic',
    'Dark midnight blue',
    'Vivid tangerine',
    'English vermillion',
    'Very pale orange',
    'Castleton green',
    'Office green',
    'Café noir',
    'Pale gold',
    'Fuchsia rose',
    'Mughal green',
    'Russet',
    'Pale brown',
    'Beaver',
    'Permanent Geranium Lake',
    'Orange Pantone',
    'Skobeloff',
    'Vue JS violet',
    'Mud',
    'Lapis lazuli',
    'Lime green',
    'Dirt',
    'Navajo white',
    'Dartmouth green',
    'Middle yellow red',
    'Champagne pink',
    'Madder Lake',
    'Cherry blossom pink',
    'Vivid mulberry',
    'Pastel orange',
    'Tuscany',
    'Icterine',
    'Vue JS Purple',
    'Denim',
    'Dark cyan',
    'Cambridge blue',
    'Green',
    'Safety orange blaze orange',
    'Old lavender',
    'Solid pink',
    'Russian violet',
    'Deep cerise',
    'Lemon curry',
    'Rose bonbon',
    'Tuscan',
    'Light periwinkle',
    'Psychedelic purple',
    'Tropical rain forest',
    'Vue JS yellow',
    'May green',
    'Spring Frost',
    'Deep Space Sparkle',
    'Morning blue',
    'Moonstone blue',
    'Deep pink',
    'Red Salsa',
    'Royal fuchsia',
    'Parchment',
    'Pale pink',
    'Dark violet',
    'Wisteria',
    'Camel',
    'Minion yellow',
    'Irresistible',
    'Very pale yellow',
    'Pale chestnut',
    'Gold Crayola',
    'Winter Wizard',
    'Popstar',
    'Laravel gold',
    'Black coral',
    'Satin sheen gold',
    'Electric purple',
    'Opera mauve',
    'Granny Smith apple',
    'Pastel green',
    'Melon',
    'Orange red Crayola',
    'Vanilla ice',
    'Philippine red',
    'Vivid orange peel',
    'Root beer',
    'Cultured',
    'Pastel brown',
    'Tangerine yellow',
    'Laravel brown',
    'Nadeshiko pink',
    'Yellow Orange',
    'Verse green',
    'Bittersweet',
    'Light salmon pink',
    'Orange soda',
    'Light cornflower blue',
    'Tractor red',
    'Mystic red',
    'Vivid yellow',
    'Amaranth deep purple',
    'Midnight blue',
    'React Native bistre',
    'Carolina blue',
    'Bdazzled blue',
    'Light yellow',
    'Snow',
    'Baby blue',
    'Vivid vermilion',
    'Prussian blue',
    'Almond',
    'Metallic Seaweed',
    'Sandy Tan',
    'Shamrock green',
    'Carrot orange',
    'Light grayish magenta',
    'Light orchid',
    'Silver foil',
    'Milk chocolate',
    'Light red ochre',
    'Middle green',
    'India green',
    'Green Munsell',
    'French lime',
    'Vue JS orange',
    'Claret',
    'Mindaro',
    'Dark jungle green',
    'Silver chalice',
    'Light carmine pink',
    'Indigo dye',
    'Copper red',
    'Amaranth red',
    'Urobilin',
    'Laravel cyan',
    'Vivid cerulean',
    'Red violet Color wheel',
    'Royal azure',
    'Generic viridian',
    'Languid lavender',
    'Mustard brown',
    'Metallic violet',
    'Persian red',
    'Metallic red',
    'Laravel scarlet',
    'Rich lilac',
    'Heat Wave',
    'Pewter Blue',
    'Tumbleweed',
    'Light steel blue',
    'Philippine gray',
    'Deep lemon',
    'Tickle Me Pink',
    'Kobicha',
    'Cyber yellow',
    'Water',
    'Metallic pink',
    'Purple navy',
    'Spring green Crayola',
    'Dark slate gray',
    'Zaffre',
    'Light cobalt blue',
    'Dark purple',
    'Baby blue eyes',
    'Pastel magenta',
    'Ripe mango',
    'Chartreuse web',
    'Ultra red',
    'Safety orange',
    'Purple Plum',
    'Antique white',
    'Redwood',
    'Pink Sherbet',
    'Royal green',
    'Tea rose',
    'Flirt',
    'Vue JS Blue Purple',
    'Vivid gamboge',
    'Eerie black',
    'Pale cerulean',
    'Vue JS Blue',
    'Medium yellow',
    'Tufts blue',
    'Violet crayola',
    'Light slate gray',
    'Metallic gold',
    'Laravel dark green',
    'Ochre',
    'Blue',
    'Light violet',
    'Raspberry glace',
    'Green Sheen',
    'Gainsboro',
    'Bright lilac',
    'Phlox',
    'Hot pink',
    'Royal orange',
    'Khaki Light khaki',
    'Rosy brown',
    'Liver organ',
    'Slate blue',
    'Peridot',
    'French rose',
    'Lavender mist',
    'Burnished brown',
    'Philippine golden yellow',
    'Naples yellow',
    'Olive green',
    'Light salmon',
    'Lavender gray',
    'Mantis',
    'Paradise pink',
    'Red strawberry',
    'Royal red',
    'Lanzones',
    'Black olive',
    'Dark goldenrod',
    'Laravel Carrot',
    'Plump Purple',
    'Quartz',
    'Earth yellow',
    'Little girl pink',
    'Ghost white',
    'Vista blue',
    'Golden brown',
    'Bitter lemon',
    'Banana Mania',
    'Rosewood',
    'Sizzling Red',
    'Tangerine',
    'Sunglow',
    'Deep sky blue',
    'React Native red',
    'Bright maroon',
    'Magenta',
    'Laravel pink',
    'Pomp and Power',
    'OU Crimson red',
    'Golden poppy',
    'Salmon Rose',
    'Philippine brown',
    'Marigold',
    'Light turquoise',
    'Manatee',
    'Light French beige',
    'Sky blue Crayola',
    'Zinnwaldite',
    'Light orange',
    'Laravel yellow',
    'Quick Silver',
    'Absolute Zero',
    'Old mauve',
    'Blast off bronze',
    'Lemon glacier',
    'British racing green',
    'China rose',
    'Pink orange',
    'Pale magenta',
    'French raspberry',
    'Silver',
    'Cadmium orange',
    'Heliotrope gray',
    'Tyrian purple',
    'Royal blue',
    'Sea blue',
    'Red Pantone',
    'Cerise',
    'Slate gray',
    'Vivid sky blue',
    'Bud green',
    'Black leather jacket',
    'Smokey Topaz',
    'Dark green',
    'Cadet grey',
    'Periwinkle Crayola',
    'Laravel purple',
    'Jade',
    'Cordovan',
    'Amethyst',
    'Amber',
    'Davys grey',
    'Taupe',
    'Orange Soda',
    'Sandstorm',
    'React Native crimson',
    'Mordant red 19',
    'Metallic orange',
    'Tulip',
    'Dark pastel green',
    'Middle blue',
    'Lemon chiffon',
    'Blue green',
    'Saddle brown',
    'Chestnut',
    'Light goldenrod yellow',
    'Avocado',
    'Rose pink',
    'Macaroni and Cheese',
    'Watermelon Yellow',
    'Cedar Chest',
    'Dark red',
    'Piggy pink',
    'Dogwood rose',
    'Tomato sauce',
    'Tomato',
    'Platinum',
    'French pink',
    'Sky magenta',
    'Seal brown',
    'Electric lime',
    'Dark orange',
    'Topaz',
    'Schauss pink',
    'Light hot pink',
    'Spring green',
    'Hookers green',
    'Orange web',
    'Orange color wheel',
    'Navy blue Crayola',
    'Vampire black',
    'Air superiority blue',
    'React Native yellow',
    'Harvest gold',
    'Sea Serpent',
    'Rose red',
    'Lavender purple',
    'Egyptian blue',
    'Kelly green',
    'Feldgrau',
    'Mint',
    'Sand',
    'Midnight green eagle green',
    'Mango',
    'French bistre',
    'Puce red',
    'Turquoise Surf',
    'Light medium orchid',
    'Blue bell',
    'Fiery rose',
    'Copper',
    'Booger Buster',
    'Periwinkle',
    'Dark raspberry',
    'Fuzzy Wuzzy',
    'Purple pizzazz',
    'Laravel tangerine',
    'Steel Teal',
    'React Native purple',
    'Medium red violet',
    'Radical Red',
    'Medium taupe',
    'Ivory',
    'Lion',
    'Light chocolate cosmos',
    'Apricot',
    'Myrtle green',
    'Verdigris',
    'Dark blue',
    'Columbia Blue',
    'Indian yellow',
    'Medium green',
    'Jungle green',
    'Purpureus',
    'Fallow',
    'Pictorial carmine',
    'Pearl Aqua',
    'Russian green',
    'Old heliotrope',
    'Dark liver',
    'Red purple',
    'Yellow Munsell',
    'Lime color wheel',
    'Fulvous',
    'Screamin Green',
    'Gunmetal',
    'Royal blue',
    'Candy pink',
    'Persimmon',
    'Bisque',
    'French violet',
    'Amaranth pink',
    'Dark lava',
    'Laravel gray',
    'Pale magenta pink',
    'Vegas gold',
    'Rose Dust',
    'Samsung blue',
    'Banana yellow',
    'React Native gray',
    'Fuchsia',
    'Light goldenrod',
    'Copper rose',
    'Maize Crayola',
    'Amaranth purple',
    'Old lace',
    'Pale carmine',
    'Jet',
    'Buff',
    'Licorice',
    'Big Foot Feet',
    'Vivid burgundy',
    'Maroon',
    'Orange peel',
    'Green blue',
    'Philippine green',
    'Outrageous Orange',
    'Medium spring green',
    'Stop red',
    'Oxley',
    'Vivid orchid',
    'Orioles orange',
    'Dark sea green',
    'Metallic Sunburst',
    'Linen',
    'Rajah',
    'Metallic blue',
    'Slimy green',
    'Fern green',
    'Vanilla',
    'Dark byzantium',
    'Dark brown',
    'Lavender web',
    'Eton blue',
    'Spiro Disco Ball',
    'Raw Sienna',
    'Ultramarine blue Caran dAche',
    'Turquoise green',
    'Laravel red',
    'Peach',
    'English violet',
    'Shadow',
    'Pale robin egg blue',
    'Tango pink',
    'Polished Pine',
    'Phthalo blue',
    'Dark spring green',
    'Brilliant rose',
    'Sandy taupe',
    'Peru',
    'Wenge',
    'Spring bud',
    'Navy purple',
    'Thulian pink',
    'Onyx',
    'Vivid crimson',
    'Mint green',
    'Bright yellow Crayola',
    'Medium carmine',
    'Bole',
    'Orange red',
    'Persian green',
    'Chinese red',
    'Pale turquoise',
    'International orange aerospace',
    'China pink',
    'Blue Pantone',
    'Very light malachite green',
    'Teal green',
    'Big dip o’ruby',
    'Pastel blue',
    'Rich carmine',
    'White',
    'Lemon meringue',
    'Middle grey',
    'Hunter green',
    'Chocolate traditional',
    'Forest green traditional',
    'Dim gray',
    'Light gold',
    'African violet',
    'Android green',
    'Medium slate blue',
    'Medium purple',
    'Ash grey',
    'Gamboge',
    'Pink Diamond Independent Retailers Colors',
    'Blue sapphire',
    'Nyanza',
    'Lemon yellow',
    'Vivid malachite',
    'Wine',
    'Milk',
    'React Native violet',
    'Crimson UA',
    'Robin egg blue',
    'School bus yellow',
    'Champagne',
    'Lotion blue',
    'Middle red purple',
    'Taupe gray',
    'Silver Lake blue',
    'Green pigment',
    'Alabaster',
    'Steel pink',
    'Metallic yellow',
    'Orange yellow Crayola',
    'Dark sienna',
    'Yellow green',
    'Royal red',
    'Wheat',
    'Blueberry',
    'Mardi Gras',
    'Vivid tangelo',
    'Pastel red',
    'Palatinate purple',
    'Pink raspberry',
    'Jasmine',
    'Lavender blue',
    'Medium electric blue',
    'Veronica',
    'Pale taupe',
    'Vermilion',
    'Sandy brown',
    'Middle purple',
    'Ruber',
    'Prilly blue',
    'Thistle Crayola',
    'Majorelle Blue',
    'Goldenrod',
    'Patriarch',
    'Cream',
    'Light cyan',
    'Red orange Color wheel',
    'Venetian red',
    'Tuscan brown',
    'Fuchsia purple',
    'Lemon iced tea',
    'Baby pink',
    'Tangelo',
    'Strawberry red',
    'Ocean blue',
    'Livid',
    'Auburn',
    'French fuchsia',
    'Frostbite',
    'Blue Munsell',
    'Raisin black',
    'Lust',
    'Red violet Crayola',
    'Mystic',
    'Ogre Odor',
    'Turquoise blue',
    'Vivid amber',
    'Pale violet red',
    'Medium vermilion',
    'Vivid auburn',
    'Violet blue Crayola',
    'Deep chestnut',
    'Red Munsell',
    'Light mustard',
    'Bright pink',
    'Xanadu',
    'Kombu green',
    'Titanium yellow',
    'Aero',
    'Antique fuchsia',
    'Rackley',
    'Chinese violet',
    'Stil de grain yellow',
    'Glaucous',
    'Dingy Dungeon',
    'Vue JS Green Yellow',
    'Pumpkin',
    'Medium pink',
    'Cyan',
    'Keppel',
    'Cerulean frost',
    'Rich maroon',
    'Strawberry',
    'St. Patricks blue',
    'Sinopia',
    'Coffee',
    'Teal',
    'Tigers eye',
    'Black Shadows',
    'Green Lizard',
    'Thistle',
    'Light sky blue',
    'Pale green',
    'Sunny',
    'Bittersweet shimmer',
    'Carmine',
    'Green blue Crayola',
    'Kobi',
    'React Native orange',
    'Light deep pink',
    'Wintergreen Dream',
    'Hollywood cerise',
    'Quincy',
    'Light red',
    'Unmellow yellow',
    'Pistachio',
    'Quinacridone magenta',
    'Lavender floral',
    'Shimmering Blush',
    'Jazzberry jam',
    'Light taupe',
    'Burnt umber',
    'Royal brown',
    'Sienna',
    'Cerulean blue',
    'French beige',
    'Burlywood',
    'Rich brilliant lavender',
    'Titanium',
    'Sea green Crayola',
    'Dark electric blue',
    'Old burgundy',
    'Lemon lime',
    'Amazon',
    'Peach yellow',
    'Field drab',
    'Waterspout',
    'Vivid orange',
    'Cocoa brown',
    'Straw',
    'Medium violet red',
    'Oxblood',
    'Salmon pink',
    'Spartan Crimson',
    'Cadmium yellow',
    'Harlequin',
    'Vue JS pink',
    'Mimi pink',
    'Microsoft red',
    'Rose quartz',
    'Medium champagne',
    'Bright green',
    'Moonstone',
    'Dark khaki',
    'Pacific Blue',
    'Raspberry rose',
    'Tenné tawny',
    'Medium sea green',
    'Mocha',
    'Sonic silver',
    'Lenurple',
    'Cyclamen',
    'Bone',
    'Charm pink',
    'Zebra White',
    'Key lime',
    'Shandy',
    'Cadmium red',
    'Navy blue',
    'Tuscan red',
    'Metallic brown',
    'Hansa yellow',
    'French blue',
    'Tan',
    'Paynes grey',
    'Coconut',
    'Light blue',
    'Pale cyan',
    'Philippine gold',
    'Philippine blue',
    'Sweet Brown',
    'Philippine yellow',
    'Red Crayola',
    'Limerick',
    'Vivid violet',
    'Aqua',
    'Dark slate blue',
    'Yellow Crayola',
    'Light brown',
    'Smoky black',
    'Fluorescent blue',
    'Rifle green',
    'Wine red',
    'Philippine violet',
    'French lilac',
    'Pale aqua',
    'Isabelline',
    'Plum',
    'French mauve',
    'Rose quartz pink',
    'Rhythm',
    'Orange iced tea',
    'Caribbean green',
    'Café au lait',
    'Charcoal',
    'Philippine silver',
    'Tan Crayola',
    'Yellow green Crayola',
    'Lavender rose',
    'Baby powder',
    'Lava',
    'Persian pink',
    'Blood red',
    'Nickel',
    'Pale blue',
    'Shadow blue',
    'Flame',
    'Cameo pink',
    'Medium orchid',
    'Olive drab',
    'Violet',
    'Persian plum',
    'Coral pink',
    'Laravel green',
    'Hot magenta',
    'Rum',
    'Cerulean',
    'Electric blue',
    'Dark olive green',
    'Glossy grape',
    'Pale cornflower blue',
    'Phthalo green',
    'Shiny Shamrock',
    'Spicy mix',
    'Turkish rose',
    'Teal deer',
    'Laser Lemon',
    'Persian rose',
    'Celadon',
    'Mexican pink',
    'Outer space Crayola',
    'Lilac Luster',
    'Police blue',
    'Mango Tango',
    'Strawberry iced tea',
    'Cerulean Crayola',
    'Lincoln green',
    'Rebecca Purple',
    'Lawn green',
    'Floral white',
    'Vue JS Blue Green',
    'Turquoise',
    'Laravel green',
    'Yellow process',
    'Vue JS red',
    'Brown web',
    'Ming',
    'Metallic green',
    'Fandango pink',
    'Yellow Pantone',
    'Mahogany',
    'Pale copper',
    'Persian indigo',
    'Dodger blue',
    'Imperial red',
    'Honeydew',
    'Crimson',
    'Microsoft green',
    'Steel blue',
    'Lavender pink',
    'Twilight lavender',
    'Red rum',
    'Brick red',
    'Very light tangelo',
    'Artichoke',
    'Bistre',
    'Silver pink',
    'Dark blue gray',
    'Rubine red',
    'Non photo blue',
    'Lemon lime',
    'Aero blue',
    'Metallic bronze',
    'Ultra pink',
    'Pale spring bud',
    'Ultramarine blue',
    'Fire engine red',
    'React Native green',
    'Roast coffee',
    'Prune',
    'Eggshell',
    'Inchworm',
    'Bleu de France',
    'Black',
    'Purple taupe',
    'Little boy blue',
    'Medium Tuscan red',
    'GO green',
    'Light silver',
    'Yellow',
    'Brown sugar',
    'Cornell red',
    'Powder blue',
    'Lilac',
    'Mulberry',
    'Pixie Powder',
    'Middle red',
    'Rose ebony',
    'Pink Diamond Ace Hardware Color',
    'Mystic maroon',
    'Soap',
    'Battleship grey',
    'Queen blue',
    'Seashell',
    'Opal',
    'Wild Strawberry',
    'Resolution blue',
    'React Native viridian',
    'Prilly pink',
    'Viridian green',
    'Saffron',
    'Moccasin',
    'Jonquil',
    'UP maroon',
    'Ebony',
    'Antique bronze',
    'Dark tan',
    'Sage',
    'Forest green web',
    'Garnet',
    'Light crimson',
    'Purple mountain majesty',
    'Super pink',
    'Old silver',
    'Atomic tangerine',
    'Bright turquoise',
    'Red violet',
    'Salem',
    'Prilly red',
    'New Car',
    'Razzle dazzle rose',
    'Raspberry pink',
    'Smoke',
    'Mandarin',
    'Lavender blush',
    'Blanched almond',
    'Green cyan',
    'Middle blue green',
    'Red orange Crayola',
    'Chocolate web',
    'Electric indigo',
    'Papaya whip',
    'Independence',
    'Italian sky blue',
    'Violet red',
    'Asparagus',
    'Menthol',
    'Ruby',
    'Mustard',
    'Persian orange',
    'Mellow yellow',
    'Misty rose',
    'Green yellow',
    'Telemagenta',
    'Pearly purple',
    'Blue pigment',
    'Bronze',
    'Byzantine',
    'Burgundy',
    'Red devil',
    'Maastricht Blue',
    'Coyote brown',
    'Napier green',
    'Byzantium',
    'Safety yellow',
    'Scarlet',
    'Lumber',
    'Cotton candy',
    'Medium sky blue',
    'New York pink',
    'Pastel pink',
    'Silver sand',
    'Green yellow Crayola',
    'React Native blue',
    'Cool grey',
    'Sapphire blue',
    'True blue',
    'Antique brass',
    'Very light blue',
    'Smalt Dark powder blue',
    'Ruby red',
    'Fashion fuchsia',
    'White coffee',
    'Old moss green',
    'Fuchsia Crayola',
    'Space cadet',
    'Arylide yellow',
    'Sand dune',
    'Antique ruby',
    'Purple Munsell',
    'Sunburnt Cyclops',
    'Red pigment',
    'Illuminating emerald',
    'Lavender magenta',
    'Light Thulian pink',
    'Pear',
    'Viridian',
    'Blizzard blue',
    'Sea Foam Green',
    'Blue violet',
    'Sunset orange',
    'Dutch white',
    'Dark turquoise',
    'Cinereous',
    'Cornflower blue Crayola',
    'Congo pink',
    'Mauvelous',
    'Rose taupe',
    'Gold',
    'Candy apple red',
    'Cosmic cobalt',
    'Beige',
    'Fire opal',
    'Yellow Sunshine',
    'Pink lace',
    'Blush',
    'Sasquatch Socks',
    'Shocking pink',
    'Lotion pink',
    'Microsoft blue',
    'Lime web green',
    'Plum web',
    'Blue yonder',
    'Bright navy blue',
    'Vivid red',
    'Deep Taupe',
    'Denim Blue',
    'Barbie pink',
    'Unbleached silk',
    'Peach puff',
    'Pale goldenrod',
    'Pale silver',
    'Blue Crayola',
    'Wood brown',
    'Twitter blue',
    'Carnation pink',
    'Weldon Blue',
    'La Salle green',
    'Pink Pantone',
    'Sunray',
    'Philippine bronze',
    'Blue gray',
    'Tropical violet',
    'Sheen green',
    'Watermelon red',
    'Silver Crayola',
    'Meat brown',
    'Deep jungle green',
    'Mango green',
    'United Nations blue',
    'Umber',
    'Violet blue',
    'Lemon',
    'Philippine pink',
    'Pine tree',
    'Iris',
    'Mode beige',
    'Light apricot',
    'Electric violet',
    'Pink flamingo',
    'Silver Metallic',
    'Orange Crayola',
    'Cinnamon Satin',
    'Rose',
    'Dark orchid',
    'Coral',
    'Smitten',
    'Vue JS yellow red',
    'Microsoft Edge blue',
    'Tuscan tan',
    'Burnt sienna',
    'Midnight blue',
    'Princess Perfume',
    'Very light azure',
    'Laravel blue',
    'Scarlet',
    'Star command blue',
    'Vivid cerise',
    'Orange yellow',
    'Cadmium green',
    'Windsor tan',
    'Otter brown',
    'React Native carmine',
    'Baker Miller pink',
    'Cornflower blue web',
    'Japanese carmine',
    'Cadet blue',
    'Philippine orange',
    'Oxford blue',
    'Medium violet',
    'Ocean green',
    'Toolbox',
    'Liver dogs',
    'Shampoo',
    'Laravel fuchsia',
    'Old rose',
    'Middle blue purple',
    'Vue JS Green',
    'Wild orchid',
    'Shocking pink Crayola',
    'Rose vale',
    'White chocolate',
    'Sapphire',
    'Red',
    'Barn red',
    'Pastel gray',
    'Fawn',
    'Coquelicot',
    'Pakistan green',
    'Smashed Pumpkin',
    'Medium spring bud',
    'Tiffany Blue',
    'Medium aquamarine',
    'Cosmic latte',
    'Sacramento State green',
    'Kobe',
    'Orange',
    'Melon Crayola',
    'React Native sky blue',
    'Rufous',
    'Tooth',
    'Chartreuse traditional',
    'Princeton orange',
    'Laurel green',
    'Caput mortuum',
    'Duke blue',
    'Mountbatten pink',
    'Mulberry Crayola',
    'Olivine',
    'Arctic lime',
    'Beau blue',
    'Paris Green',
    'Dark salmon',
    'Misty Moss',
    'Zomp',
    'Azure',
    'Forest green Crayola',
    'Laravel silver',
    'Mellow apricot',
    'Liver chestnut',
    'International orange Golden Gate Bridge',
    'Desert',
    'Celeste',
    'Medium blue',
    'YInMn Blue',
    'Eucalyptus',
    'Philippine sky blue',
    'Malachite',
    'Light sea green',
    'Pink',
    'Fandango',
    'Ultramarine',
    'Ao English',
    'Midnight',
    'Pullman Green',
    'Medium ruby',
    'Mountain Meadow',
    'Mint cream',
    'Vivid raspberry',
    'Sizzling Sunrise',
    'Raw umber',
    'Lotion',
    'Roman silver',
    'Cornsilk',
    'Golden yellow',
    'Ecru',
    'Maya blue',
    'Razzmatazz',
    'Firebrick',
    'Gold Fusion',
    'Heliotrope',
    'Vine Green',
    'Royal purple',
    'Rusty red',
    'Pink lavender',
    'Sap green',
    'Red brown',
    'Deep champagne',
    'Citrine',
    'Pine green',
    'Pastel violet',
    'Medium candy apple red',
    'Medium Persian blue',
    'Tart Orange',
    'Deep mauve',
    'Sugar Plum',
    'Orchid pink',
    'Portland Orange',
    'Brown',
    'Brink pink',
    'Orchid',
    'Cobalt blue',
    'Ocean boat blue',
    'Wine dregs',
    'Medium orange',
    'Tea rose',
    'Dark moss green',
    'Vermilion',
    'Light pink',
    'Liseran purple',
    'Maize',
    'Brunswick green',
    'Temptress',
    'Black bean',
    'Purple Heart',
    'Parrot Pink',
    'Willpower orange',
    'Falu red',
    'Metallic silver',
    'Pale red violet',
    'Emerald',
    'Violet Caran dAche',
    'French sky blue',
    'Mikado yellow',
    'Indigo',
    'Mauve',
    'Sea green',
    'Moss green',
    'Cardinal',
    'Sunset',
    'Yellow rose',
    'Timberwolf',
    'Palm Leaf',
    'Palatinate blue',
    'Medium jungle green',
    'Amber two',
    'Mummys Tomb',
    'Queen pink',
    'Aquamarine',
    'Iceberg',
    'Vue JS Red Purple',
    'Light green',
    'International orange engineering',
    'Green Pantone',
    'Light fuchsia pink',
    'Microsoft yellow',
    'Vivid lime green',
    'Alloy orange',
    'Yellow Orange Color Wheel',
    'Rose madder',
    'Violet color wheel',
    'Picton blue',
    'Light coral',
    'Royal pink',
    'Pearl',
    'Rich electric blue',
    'Khaki web Khaki',
    'Tea green',
    'Blue jeans',
    'Copper penny',
    'Gold web Golden',
    'Sepia',
    'Medium turquoise',
    'Paolo Veronese green',
    'Bottle green',
    'Watermelon',
    'Violet web',
    'English red',
    'Green Crayola',
    'Vivid red tangelo',
    'Violin Brown',
    'Cyber grape',
    'Alice blue',
    'Salmon',
    'Citron',
    'Light gray',
    'Middle green yellow',
    'Lavender indigo',
    'Pale lavender',
    'Honolulu blue',
    'Liver',
    'Old gold',
    'Aureolin',
    'Outer Space',
    'Medium red',
    'Razzmic Berry',
    'Pullman Brown',
    'Dark sky blue',
    'Peach orange',
    'Eggplant',
    'Philippine indigo',
    'Pastel purple',
    'Rose garnet',
    'Rich lavender',
    'Persian blue',
    'Sky blue',
    'Mauve taupe',
    'Liberty',
    'Flax',
    'Celadon green',
    'Pale violet',
    'Dark gray X11',
    'Army green',
    'Pansy purple',
    'Indian red',
    'Rust',
    'Rose gold',
    'Deep fuchsia',
    'Van Dyke brown',
    'Bistre brown',
    'Granite gray',
    'Selective yellow',
    'Canary yellow',
    'Han purple',
    'Teal blue',
    'Gray web',
    'Burnt orange',
    'Middle yellow',
    'Mustard green',
    'Amaranth',
    'Medium lavender magenta',
    'Turtle green',
    'Winter Sky',
    'Upsdell red',
    'June bud',
    'Han blue',
    'Pale plum',
    'Japanese violet',
    'Rocket metallic',
    ];
}
